### ISSUE TITLE
use ID or channel name instead of username

### ISSUE THREAD

**Issue by a7wazian** [Delafault/Telegram-copy-paste-bot#1]
very good
I want to use ID or channel name instead of username

please guide me

Like the robot above, which uses the channel name instead of the username
https://github.com/nTorre/TelegramCopier

**Comment by Delafault** [comment]
Thanks.
You can safely specify the id of the channel, just like @username:
![image](https://github.com/Delafault/Telegram-copy-paste-bot/assets/78411508/7e0df4cc-cbb5-45d5-bebf-e337b090b23d)
You can't specify a channel name, because you can name a channel anything you want, but each one will have a unique id.
